### ISSUE TITLE
Problem starting downgrade.

### ISSUE THREAD

**Issue by Boured** [profi200/sysUpdater#18]
Hello I have a problem, I have all the necessary files all in the correctly named "updates" folder. Though when I launch the sysUpdater 0.4.1 and press Y, it displays a really fast message which I could only read the word "Terminated" before kicking me to the Homebrew Launcher. Is this something to do with the extra permissions mentioned in the releases page?, and if so what do I need to do to make it downgrade?

Sorry if this is a simple fix, I is a noob at Homebrew

System: 2DS running version 10.3.0-28U and wanting to downgrade to 9.2.0-20U

**Comment by profi200** [comment]
Did you download the release from this repo or from elsewhere? Because the one from this repo does not have memchunkhax v2 attached so it will fail due to missing permissions.
It does close so fast because the latest public release has some informations missing to make exceptions work right.

**Comment by Boured** [comment]
I downloaded it from here, though I have never heard of memchunkhax v2 so thanks :3

**Comment by Boured** [comment]
Nevermind, found the working one and am now using 9.2, thank you for your help :3

**Comment by Phantom522** [comment]
i have same problem, can u give me working line

**Comment by Boured** [comment]
Here you go ^^

https://gbatemp.net/attachments/sysupdater-zip.34449/

**Comment by huahaha** [comment]
Hi Profi200,

sorry if this is out of topic, just want to ask.
i'm updating EmuNAND of my N3DS Japan version from 9.2 to 9.5,
i have copied all update cias to updates folder
i'm using sysupdater and then after installing several cias, it pops up an error about not having ...0CA00.cia in updates folder. then it kick me back to emuNAND home.

I was lucky i can still boot to emunand after error when installing system cia.

After much googling, I found out that i forgot to delete the ...0CA00.cia before updating.
After i delete that, i run sysupdater again and the updates kind of resume by itself, because it is not installing native_firm like it will do when first updating, then it finished successfully, i checked the system firmware and i'm on 9.5 emunand.

Is it okay to resume update like that? 
Does sysupdater have functionality to resume system update?

Or is it better for me to restore my 9.2 emunand then fresh update using sysupdater again?

Thanks and sorry for being too long explaining XD

**Comment by profi200** [comment]
It will automatically detect what is already installed by comparing versions so it is not a problem. You had luck that it was not bricked in any way.

**Comment by Phantom522** [comment]
@Boured  thanks for your link :D

**Comment by huahaha** [comment]
@profi200 
Nice, thanks for confirming. Yeah i was lucky that time :smile:
